name: GunlukOdul
main: leaderos.web.tr.dailyreward.Main
version: 2.0.3
folia-supported: true
api-version: 1.13
author: Geik
depend: [PlaceholderAPI]
commands:
  günlüködül:
    description: Ana komuttur.
